main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.auctions, name='auctions'),
    path('settings', views.settings, name='settings'),
    path('hop', views.hop_realms, name = 'hop'),
]

myah/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.db.models import Sum, F


class SortManager(models.Manager):
    def mean_price(self, realm, item_id):
        """Returns mean min price for this (realm, item_id)."""

        all_chunks = super().get_queryset().filter(realm=realm, item_id=item_id)
        if len(all_chunks) == 0:
            return 999999  # no auctions so put this realm on top

        total_quantity = all_chunks.aggregate(Sum('stack_size'))[
            'stack_size__sum']
        percentage = 0.45  # CHANGEME
        max_quantity = total_quantity * percentage
        curr_quantity = 0
        mean_numerator = 0

        for chunk in all_chunks:
            if curr_quantity + chunk.stack_size <= max_quantity or curr_quantity == 0:
                mean_numerator += chunk.stack_size * chunk.price
            else:
                break
            curr_quantity += chunk.stack_size

        return mean_numerator / curr_quantity

    def my_price_and_undercut_count(self, realm, item_id):
        """Returns price of lowest AuctionChunk owned by Realm's seller and also
        how many auctions are posted for less (undercut). Returns None if no
        auctions are posted by the seller.
        """

        auctions = super().get_queryset().filter(
            realm=realm, item_id=item_id).values_list('price', 'stack_size', 'own')

        undercut_count = 0
        my_price = None
        for auc in auctions:
            if auc[2]:
                my_price = auc[0]
                break
            else:
                undercut_count += auc[1]

        if not my_price:
            return None, None
        return my_price, undercut_count

        # seller = Realm.objects.get(name=realm).seller
        # full_name = f"{seller}-{realm.replace(' ', '')}"
        query = super().get_queryset().filter(
            realm=realm, item_id=item_id).values_list('price')
        # No chunk posted by seller
        if len(query) < 1:
            return None, None
        # Sort price_list and return lowest
        price_list = [x[0] for x in list(query)]
        price_list.sort()
        my_price = price_list[0]

        # Count how many auctions are posted for less than my_price
        query = super().get_queryset().filter(
            realm=realm, item_id=item_id, price__lt=my_price)
        undercut_count = query.aggregate(Sum('quantity'))['quantity__sum'] or 0

        return my_price, undercut_count


class AuctionChunk(models.Model):
    chunk_id = models.AutoField(primary_key=True)
    realm = models.TextField(blank=True, null=True)
    item_id = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    stack_size = models.IntegerField(blank=True, null=True)
    own = models.BooleanField(blank=True, null=True)
    time_left = models.TextField(blank=True, null=True)

    objects = models.Manager()
    sort_values = SortManager()

    @property
    def total_quantity(self):
        return self.quantity * self.stack_size

    def __str__(self):
        return str(self.price)

    class Meta:
        managed = False
        db_table = 'auction_chunks'


class AuctionId(models.Model):
    auc_id = models.IntegerField(blank=True, null=True)
    chunk = models.ForeignKey(
        AuctionChunk, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auction_ids'


class Realm(models.Model):
    name = models.TextField(primary_key=True, unique=True)
    slug = models.TextField(unique=True)
    code = models.TextField(unique=True)
    update_interval = models.IntegerField(blank=True, null=True)
    last_update = models.IntegerField(blank=True, null=True)
    #last_check = models.IntegerField(blank=True, null=True)
    json_link = models.TextField(blank=True, null=True)

    # seller = models.TextField(blank=True, null=True)
    region = models.TextField(blank=True, null=True)
    position = models.IntegerField(blank=False, null=False, default=0)
    account = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'realms'


class ItemCategory(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.TextField(unique=True)
    position = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'item_categories'


class Item(models.Model):
    item_id = models.IntegerField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    short_name = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        ItemCategory, models.DO_NOTHING, blank=True, null=True)
    position = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'items'


class StackSize(models.Model):
    row_id = models.AutoField(primary_key=True)
    stack_size = models.IntegerField()
    category = models.ForeignKey(
        ItemCategory, models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return str(self.stack_size)

    class Meta:
        db_table = 'stack_sizes'


class HopRealm(models.Model):
    name = models.TextField(primary_key=True, unique=True)
    category = models.TextField(blank=True, null=True)
    position = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'hop_realms'

main/views.py
from django.shortcuts import render, get_object_or_404

from .models import AuctionChunk, AuctionId, Realm, ItemCategory, Item, HopRealm

import json


def auctions(request):
    item_category = 3
    # get list of (item_id, name) tuples
    item_list = Item.objects.filter(category_id=item_category).values_list(
        'item_id', 'name').order_by('position')
    realms = [x[0]
              for x in Realm.objects.values_list('name').order_by('position')]

    auc_data = {}
    realm_order = {}
    for item in item_list:
        item_id = item[0]
        auc_data[item_id] = {}
        realm_order[item_id] = {}
        # order based on realm positions in Realm model
        realm_order[item_id]['position'] = realms

        # create MeanPrice ordered realm list
        temp_list = [(x, AuctionChunk.sort_values.mean_price(
            realm=x, item_id=item_id)) for x in realms]
        temp_list.sort(key=lambda x: x[1], reverse=True)
        mean_list = [x[0] for x in temp_list]
        realm_order[item_id]['mean_price'] = mean_list

        # create realm orders where seller's auction appear first and ordered by price/undercut_count
        temp_list = []
        mean_list_rest = []
        for realm in mean_list:
            my_price, undercut_count = AuctionChunk.sort_values.my_price_and_undercut_count(
                realm, item_id)
            if my_price:
                temp_list.append((realm, my_price, undercut_count))
            else:
                mean_list_rest.append(realm)
        temp_list.sort(key=lambda x: x[1], reverse=True)
        realm_order[item_id]['my_price'] = [x[0]
                                            for x in temp_list] + mean_list_rest
        temp_list.sort(key=lambda x: x[2], reverse=True)
        realm_order[item_id]['undercut_count'] = [x[0]
                                                  for x in temp_list] + mean_list_rest

        # Fetch item data from model
        default_realm_order = realm_order[item_id]['mean_price']
        for realm in default_realm_order:
            auctions = AuctionChunk.objects.filter(realm=realm, item_id=item_id).values_list(
                'price', 'quantity', 'stack_size', 'own')
            auctions = [{
                'price': x[0],
                'quantity': x[1] * x[2] / 1000,
                'own': x[3]}
                for x in auctions]
            total = sum(x['quantity'] for x in auctions)
            code = Realm.objects.filter(name=realm).values_list('code')
            # seller = '-'.join([Realm.objects.get(name=realm).seller, realm.replace(' ', '')])
            account = Realm.objects.get(name=realm).account
            slug = Realm.objects.get(name=realm).slug
            auc_data[item_id][realm] = {
                'auctions': list(auctions),
                'code': code[0][0],
                'account': account,
                'total': total,
                'slug': slug
            }

    context = {
        'item_list': item_list,
        'auc_data': auc_data,
        'realm_order': realm_order,
    }

    return render(request, 'main/auctions.html', context=context)


def settings(request):
    if request.method == "POST":
        json_data = json.loads(request.body)
        for position, realm_name in enumerate(json_data['realmOrder']):
            realm = Realm.objects.get(name=realm_name)
            realm.position = position
            realm.save()
        for position, category in enumerate(json_data['itemOrder']):
            item_category = ItemCategory.objects.get(name=category['name'])
            item_category.position = position
            item_category.save()
            for position, item_name in enumerate(category['items']):
                item = Item.objects.get(name=item_name)
                item.position = position
                item.save()

    # Realm names sorted by position field
    realms = [x[0]
              for x in Realm.objects.values_list('name').order_by('position')]
    # Items by category
    item_categories = [x[0] for x in ItemCategory.objects.values_list(
        'name').order_by('position')]
    items = {}
    for category in item_categories:
        item_list = Item.objects.filter(
            category__name=category).order_by('position')
        if len(item_list):
            items[category] = item_list

    context = {
        'realms': realms,
        'items': items,
    }

    return render(request, 'main/settings.html', context=context)


def hop_realms(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        for category in json_data.keys():
            for position, realm_name in enumerate(json_data[category]):
                realm = HopRealm.objects.get(name=realm_name)
                realm.position = position
                realm.category = None if category == 'no_category' else category
                realm.save()

    realms = {}
    categories = [x[0]
                  for x in HopRealm.objects.values_list('category').distinct()]
    for category in categories:
        realm_list = [x[0] for x in HopRealm.objects.filter(
            category=category).values_list('name').order_by('position')]
        if not category:
            category = 'no_category'
        realms[category] = realm_list

    context = {
        'realms': realms,
    }
    return render(request, 'main/hop_realms.html', context=context)

main/templates/main/auctions.html
{% extends 'main/base.html' %} {% block content %}

<div class="row">
  <!-- Tabs -->
  <div class="col">
    <ul id="item-tabs" class="tabs">
      {% for item in item_list %}
      <li class="tab"><a href="#{{ item.0 }}">{{ item.1 }}</a></li>
      {% endfor %}
    </ul>
  </div>
  <!-- Reorder Button -->
  <div id="sorting-buttons" class="col">
    <a
      data-orderby="mean_price"
      class="waves-effect waves-light btn disabled"
      style="margin-top:9px;"
      >Mean Price</a
    >
    <a
      data-orderby="my_price"
      class="waves-effect waves-light btn"
      style="margin-top:9px;"
      >My Price</a
    >
    <a
      data-orderby="undercut_count"
      class="waves-effect waves-light btn"
      style="margin-top:9px;"
      >Undercut Count</a
    >
    <a
      data-orderby="position"
      class="waves-effect waves-light btn"
      style="margin-top:9px;"
      >Position Order</a
    >
  </div>
  <!-- Item Tables (Tabs) -->
  <div id="item-tables">
    {% for item_id, item_data in auc_data.items %}
    <div id="{{ item_id }}" class="col s12">
      {% for realm, realm_data in item_data.items %}
      <div class="row" data-id="{{ realm }}" style="margin-bottom:5px;">
        <div class="col" style="width:45px;margin-top:3px;">
          <a
            href="https://theunderminejournal.com/#eu/{{realm_data.slug}}/item/168487"
            target="_blank"
          >
            {% if realm_data.account == 0 %}
            <span style="color:#ffa04d;font-size: 1.4rem;font-weight: 600;">
              {{ realm_data.code }}
            </span>
            {% elif realm_data.account == 5 %}
            <span style="color:#5294ff;font-size: 1.4rem;font-weight: 600;">
              {{ realm_data.code }}
            </span>
            {% else %}
            <span style="color:#52ffa9;font-size: 1.4rem;font-weight: 600;">
              {{ realm_data.code }}
            </span>
            {% endif %}
          </a>
          <span style="white-space:nowrap">
            {{ realm_data.total|floatformat:0 }} K
          </span>
        </div>

        <div class="col">
          <table class="highlight mytable">
            {% for auc in realm_data.auctions %} {% if forloop.counter <= 26 %}
            <tr
              class="tooltipped"
              data-position="right"
              data-tooltip="{{ auc.price }}"
            >
              {% if auc.own %}
              <td class="my-auction">{{ auc.price|floatformat:1 }}</td>
              {% else %}
              <td>{{ auc.price|floatformat:1 }}</td>
              {% endif %} {% if auc.quantity < 1.0 %}
              <td class="stack-size-100">{{ auc.quantity|floatformat:1 }} K</td>
              {% else %}
              <td class="stack-size-200">{{ auc.quantity|floatformat:1 }} K</td>
              {% endif %}
            </tr>
            {% endif %} {% endfor %}
          </table>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
</div>

<!-- for jsonData -->
{{ realm_order|json_script:"json-data" }}

<script>
  // Materialize Tooltips
  // document.addEventListener('DOMContentLoaded', function() {
  //   var elems = document.querySelectorAll('.tooltipped');
  //   var instances = M.Tooltip.init(elems, {})
  // });
  // Item Tabs Init
  M.Tabs.init(document.getElementById('item-tabs'));
  // Sorting Functionality
  let jsonData = JSON.parse(document.getElementById('json-data').textContent);
  let itemTables = document.querySelectorAll('#item-tables > div');

  // Sorting Buttons click events
  let sortingButtons = document.getElementById('sorting-buttons');
  sortingButtons.childNodes.forEach(function(el) {
    // handle text nodes
    if (el.nodeType != 3) {
      el.addEventListener('click', function() {
        sortRealms(el.dataset.orderby);
        enableSortButtons();
        el.classList.add('disabled');
      });
    }
  });

  function sortRealms(orderList) {
    // iterate over all realm tables
    itemTables.forEach(function(itemTable) {
      // array of ordered realms
      realmOrder = jsonData[itemTable.id][orderList];
      // remove and append realm rows in order
      realmOrder.forEach(function(realm) {
        queryString = '[data-id="' + realm + '"]';
        realmRow = itemTable.querySelector(queryString);
        itemTable.removeChild(realmRow);
        itemTable.appendChild(realmRow);
      });
    });
  }

  function enableSortButtons() {
    sortingButtons.childNodes.forEach(function(el) {
      if (el.nodeType != 3) {
        el.classList.remove('disabled');
      }
    });
  }
</script>
{% endblock %}

main/templates/main/base.html
{% load static %}

<head>
  <title>MyAh - Django project</title>

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
    rel="stylesheet"
  />
  <!-- Materialize CSS -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
  />
  <!-- My CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />

  <!-- Jquery JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <!-- Materialize JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <!-- Sortable JS -->
  <script src="https://raw.githack.com/SortableJS/Sortable/master/Sortable.js"></script>
</head>

<body>
  {% include 'main/base_navbar.html' %}

  <div id="content">
    {% block content %} {% endblock %}
  </div>
</body>

main/templates/main/base_navbar.html
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo right">MyAH</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="{% url 'main:auctions' %}">Auctions</a></li>
        <li><a href="{% url 'main:settings' %}">Settings</a></li>
        <li><a href="{% url 'main:hop' %}">Hopping</a></li>
        </ul>
    </div>
</nav>

main/templates/main/hop_realms.html
{% extends 'main/base.html' %}

{% block content %}
  <div id="my-sortable" class="row">
    <div class="col s2">
      <!-- Serialize Button -->
      <a id="serialize" class="waves-effect waves-light btn" style="margin-top:9px">Submit Changes</a>
      <!-- Hop List -->
      <p style="color:orange"><strong>Hop List</strong></p>
      <div class="collection" id="hop_list">
      {% for realm in realms.hop_list %}
        <div class="collection-item" data-id="{{ realm }}">{{ forloop.counter }} {{ realm }}</div>
      {% endfor %}
      </div>
    </div>
    <!-- BlackList -->
    <div class="col s2">
        <!-- Temp BlackList -->
        <p style="color:orange"><strong>Temp Competition</strong></p>
        <div class="collection" id="temp_competition">
        {% for realm in realms.temp_competition %}
          <div class="collection-item" data-id="{{ realm }}">{{ realm }}</div>
        {% endfor %}
        </div>
        <!-- Day BlackList -->
        <p style="color:orange"><strong>Today Competition</strong></p>
        <div class="collection" id="competition">
        {% for realm in realms.competition %}
          <div class="collection-item" data-id="{{ realm }}">{{ realm }}</div>
        {% endfor %}
        </div>
      </div>
    <!-- Bad -->
    <div class="col s2">
      <!-- Avoid -->
      <p style="color:orange"><strong>Permanent Competition</strong></p>
      <div class="collection" id="permanent_competition">
      {% for realm in realms.permanent_competition %}
        <div class="collection-item" data-id="{{ realm }}">{{ realm }}</div>
      {% endfor %}
      </div>
      <!-- No category -->
      <p style="color:orange"><strong>No Category</strong></p>
      <div class="collection" id="no_category">
      {% for realm in realms.no_category %}
        <div class="collection-item" data-id="{{ realm }}">{{ realm }}</div>
      {% endfor %}
      </div>
    </div>
  </div>

  {% csrf_token %}
  <script>
    // Sortables
    let sortables = {}
    let categories = ['hop_list', 'temp_competition', 'competition', 'permanent_competition', 'no_category']
    categories.forEach(function(id) {
      let el = document.getElementById(id)
      sortables[id] = Sortable.create(el, {
        group: 'shared',
        animation: 150,
      });
    });

    // Serialize for POST
    function serialize() {
      data = {};
      for (const [key, value] of Object.entries(sortables)) {
        data[key] = value.toArray();
      }
      console.log(data);
      return data;
    };

    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    // Serialize Button Click handler
    $('#serialize').click(function() {
      $.ajax({
        type: "POST",
        url: "{% url 'main:hop' %}",
        data: JSON.stringify(serialize()),
      });
    });

  </script>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12">
        <ul class="tabs">
            {% for item in items %}
                <li class="tab"><a href="#{{ item.0 }}">{{ item.1 }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% for item_id, item_data in data.items %}
    <div id="{{ item_id }}" class="col s12">
        {% for realm, realm_data in item_data.items %}
        <div class="row" style="margin-bottom:5px;">
            <div class="col" style="width:45px;">
                <p><strong>{{ realm_data.1 }}</strong></p>
            </div>
            <div class="col">
                <table class="highlight mytable">     
                {% for auc in realm_data.0 %}
                    {% if forloop.counter <= 30 %}
                        {% if auc.2 == realm_data.2 %}
                        <tr>
                            <td class="myauction"><strong>{{ auc.1|floatformat:2 }}</strong></td>
                            <td class="myauction"><strong>{{ auc.0 }}</strong></td>
                        </tr>
                        {% else %}
                        <tr>
                            <td>{{ auc.1|floatformat:1 }}</td>
                            <td>{{ auc.0 }}</td>
                        </tr>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                </table>
            </div>  
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

<script>
    var el = $('.tabs').first()[0];
    var instance = M.Tabs.init(el);
</script>

{% endblock %}

main/templates/main/settings.html
{% extends 'main/base.html' %}

{% block content %}
  <div id="my-sortable" class="row">
    <!-- Realms Sortable -->
    <div class="collection col s2 my-collection" id="sort-list-realm">
    {% for realm in realms %}
      <div class="collection-item" data-id="{{ realm }}">{{ realm }}</div>
    {% endfor %}
    </div>

    <!-- Items Sortable-->
    <div class="collection col s2 my-collection" id="sort-list-category">
    {% for category, item_list in items.items %}
      <div class="collection-item" data-id="{{ category }}">
        <div class="category-name" align="center"><strong>{{ category }}</strong></div>
        <div class="collection">
        {% for item in item_list %}
          <div class="collection-item" data-id="{{ item }}">{{ item }}</div>
        {% endfor %}
        </div>
      </div>
    {% endfor %}
    </div>

    <!-- Serialize Button -->
    <div class="col s2">
      <a id="serialize" class="waves-effect waves-light btn" style="margin-top:9px;">Submit Changes</a>
    </div>
  </div>

  {% csrf_token %}
  <script>
    // Realm Sortable
    let realmList = document.getElementById('sort-list-realm');
    const realmSortable = Sortable.create(realmList, {animation: 150, });
    // Category Sortable
    let categoryList = document.getElementById('sort-list-category');
    const categorySortable = Sortable.create(categoryList, {animation: 150, });
    // Items Sortables
    let itemLists = categoryList.querySelectorAll('#sort-list-category > div');
    let itemSortables = {};
    itemLists.forEach(function(el) {
      itemSortables[el.dataset.id] = Sortable.create(el.querySelectorAll('div')[1], {animation: 150, });
    });

    function serialize() {
      realmOrder = realmSortable.toArray();

      itemOrder = Array();
      categorySortable.toArray().forEach(function(el) {
        category = {
          'name': el,
          'items': itemSortables[el].toArray(),
        }
        itemOrder.push(category)
      });
      console.log({
        'realmOrder': realmOrder,
        'itemOrder': itemOrder
      })
      return {
        'realmOrder': realmOrder,
        'itemOrder': itemOrder
      }
    };

    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    // Serialize Button Click handler
    $('#serialize').click(function() {
      $.ajax({
        type: "POST",
        url: "{% url 'main:settings' %}",
        data: JSON.stringify(serialize()),
      });
    });

  </script>
{% endblock %}